### ISSUE TITLE
Investigate Performance Impact of bpmn-js@9 on Phantom-JS

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/bpmn-js-integration#17]
__What should we do?__

With bpmn-js@9, import [complex.bpmn](https://github.com/bpmn-io/bpmn-js-integration/blob/a8f413990637c66941682a2e54315b2610535c31/test/spec/base/diagrams/complex.bpmn) takes ~25% longer on Chrome than on bpmn-js@8

However, on CI the complex check takes ~25000ms instead of ~4000ms before. We should investigate why the performance impact is so high in phantomJS

`bpmn-js@9` `viewer.open` timings
![image](https://user-images.githubusercontent.com/21984219/154690233-78fd4cb2-6040-49a2-a2d7-6ed7cb45a39e.png)

`bpmn-js@8` `viewer.open` timings
![image](https://user-images.githubusercontent.com/21984219/154690167-27ca3f36-3019-4aac-a559-88dfb3ef09cb.png)

__Why should we do it?__
We need to ensure that this does not impact users and is only isolated to phantomJS/CI runs

**Comment by marstamm** [comment]
Side note: just changing the timeout from `500` to `10` reduces test time by half

**Comment by nikku** [comment]
Let's close this. PhantomJS is dead.
