### ISSUE TITLE
Mocha Tests are failing with "Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called"

### ISSUE THREAD

**Issue by asoahc** [bpmn-io/bpmn-js-integration#3]
Hi,

I try to get in touch with some integration tests for bpmn-js.
Unfortunately, after installation all mocha tests are failing with the same error: 

(just as example: append events)
```
Running "test" task

Running "mochaTest:test" (mochaTest) task

  modeling
    append
      1) should append events


  0 passing (25s)
  1 failing

  1) modeling
       append
         should append events:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\mypath\bpmn-js-integration\test\spec\modeling\modeling.js)
```
During the execution the output files are created in the tmp-Folder. Therefore I assume that only the comparison does not work.

I have no clue how to change the code to get the tests running.
Could you have a look?

Many Thanks,
aSoahc

**Comment by nikku** [comment]
What exact commands did you execute to end up in this situation?

The following works for me:

```
git clone git@github.com:bpmn-io/bpmn-js-integration.git
cd bpmn-js-integration
npm install
npm run all
```

**Comment by asoahc** [comment]
Hi Nikku,

I performed it again with your instructions, but received the same result:

```
....
  57) base
       import <wrap-poolname.bpmn>:
     Error: Timeout of 4000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\ympath\bpmn-js-integration\test\spec\base\base.js)




Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! bpmn-js-integration@0.0.1 all: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the bpmn-js-integration@0.0.1 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Regards,
aSoahc

**Comment by nikku** [comment]
Please share your environment:

* Operating System
* Java Version (`java -version` on the command line)

**Comment by asoahc** [comment]
Hi Nikku,

my operating system is Windows 10 (Version 1703) and Java version is "1.8.0_161".

Many Thanks for your support,
aSoahc

**Comment by nikku** [comment]
@philippfromme Could you have a look whether you are able to run the test suite on windows?

**Comment by philippfromme** [comment]
On my machine (Windows 10, Java 10.0.2) the suite fails, too. 😞

**Comment by nikku** [comment]
That is great. Could you figure out why? :man_dancing:

**Comment by nikku** [comment]
We figured out why stuff is breaking on windows. Should work with the latest master snapshot.

**Comment by asoahc** [comment]
Hi nikku, Hi philippfromme,

thank you very much for your investigation.
Unfortunately, now I receive the next error ...


 ```
 0 passing (2m)
  57 failing

  1) modeling
       append
         should append events:
     Uncaught Error: spawn javac ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  

  2) modeling
       append
         should append text-annotations:
     Uncaught Error: spawn javac ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
````

Maybe this is something similar to this ticket, I found on another project.
https://github.com/nodejs/node-v0.x-archive/issues/5841

Best Resgards,
aSoahc

**Comment by asoahc** [comment]
Could you re-open this issue?

**Comment by nikku** [comment]
This is probably due to the fact that you do not have a JDK with `javac` installed.

**Comment by asoahc** [comment]
Thanks again.
After setting the PATH variable to javac, the test is running.

Many Thanks for your support,
aSoahc
