### ISSUE TITLE
Mocha tests failing with "Failed to instantiate component"

### ISSUE THREAD

**Issue by asoahc** [bpmn-io/bpmn-js-integration#9]
Hi,

I try to run the integration test out of the box, but all Mocha Tests are failing with following error:

**Failed to instantiate component**

`Running "test" task

Running "mochaTest:test" (mochaTest) task

  modeling
    append
  Failed to instantiate component
    file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:23513
file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:659:68
SaveCommand@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:736:6
call@[native code]
invoke@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:49453:25
_registerCommand@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:204:74
Initializer@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:338:23
Initializer@[native code]
instantiate@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:49445:100
get@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:49405:43
file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:23511:57
forEach@[native code]
bootstrap@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:23506:21
createInjector@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:23540:19
Diagram@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:23595:56
_init@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:1747:27
BaseViewer@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:1180:13
BaseModeler@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:1059:28
Modeler@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:2083:29
test@file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/tmp/integration/modeling/append/events.html:48:50

  file:///C:/Users/Documents/localDevEnv/bpmn-js-integration/dist/bpmn.js:23514`

__Steps to Reproduce__

I just performed the following steps:

- git clone git@github.com:bpmn-io/bpmn-js-integration.git
- cd bpmn-js-integration
- npm install
- npm run all

__Environment__

- OS: Windows 10
- Java Version: 1.8.0_251
- JAVA SDK: 14.0.1

Best Regards, aSoahc

**Comment by philippfromme** [comment]
The issue is that we released a `v1.3.1` that uses promises and the `async` keyword. Since this project has a dependency on `bpmn-js-cli: "^1.0.0"` an install will now install `v1.3.1` which doesn't work with PhantonJS.
